<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2011-06-27 18:38

$extensionPath = t3lib_extMgm::extPath('message_queue');
$extensionClassesPath = t3lib_extMgm::extPath('message_queue') . 'classes/';
return array(
	'tx_messagequeue_message' => $extensionClassesPath . 'class.tx_messagequeue_message.php',
	'tx_messagequeue_queue' => $extensionClassesPath . 'class.tx_messagequeue_queue.php',
	'tx_messagequeue_backend_DbBackend' => $extensionClassesPath . 'backend/class.tx_messagequeue_backend_dbbackend.php',
	'tx_messagequeue_worker_Worker' => $extensionClassesPath . 'interfaces/interface.tx_messagequeue_worker_worker.php',
	'tx_messagequeue_worker_AbstractWorker' => $extensionClassesPath . 'worker/class.tx_messagequeue_worker_abstractworker.php',
	'tx_messagequeue_worker_Message' => $extensionClassesPath . 'worker/class.tx_messagequeue_worker_message.php',
	'tx_messagequeue_scheduler_WorkerTask' => $extensionPath . 'scheduler/class.tx_messagequeue_scheduler_workertask.php',
	'tx_messagequeue_scheduler_WorkerTask_additionalfieldprovider' => $extensionPath . 'scheduler/class.tx_messagequeue_scheduler_workertask_additionalfieldprovider.php',
);
?>